<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Data Structure (object) defined in Numpy is an N-dimentional array called**

In [14]:
import numpy as np

In [17]:
#Syntax
#array_name = np.array(data, dtype = None, ndimin = 0)



1.   Object - Any object exposing the array interface
method returns an array, or any(nested) sequence
2.   dtype - Desired data type of array, optional
3. ndimin - Minimum dimension of resultant array


In [18]:
a1 = np.array([1,2,3])
print(a1, '\n type', type(a1))

[1 2 3] 
 type <class 'numpy.ndarray'>


In [22]:
a2 = np.array([[1,2],[4,5]])
print(a2)

[[1 2]
 [4 5]]


**DIMENSION**

In [23]:
# dimension: 2
a3 = np.array([1,2,3], ndmin= 2)
print(a3)

[[1 2 3]]


**Data Type**

In [24]:
# Dtype parameter
a4 = np.array([1,2,3], dtype = 'int32')
print(a4, '\n dtype:', a4.dtype)

[1 2 3] 
 dtype: int32


**Reshape**

In [25]:
a5 = np.array([[1,2,3],[4,5,6]])
print(a5, '\n shape:', a5.shape)
a5.shape = (3,2)
print(a5, '\n shape:', a5.shape)

[[1 2 3]
 [4 5 6]] 
 shape: (2, 3)
[[1 2]
 [3 4]
 [5 6]] 
 shape: (3, 2)


In [26]:
a6 = np.array([[1,2,3],[4,5,6]])
print(a6, '\n shape:', a6.shape)
a7 = a6.reshape(3,2)
print(a7, '\n shape:', a7.shape)

[[1 2 3]
 [4 5 6]] 
 shape: (2, 3)
[[1 2]
 [3 4]
 [5 6]] 
 shape: (3, 2)


**Sequence**

Stntax:
numpy.arange(start,stop,step,dtype =None)

In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(np.arange(1,10,0.5))


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


**Array of specified size, filled with zeros**

In [4]:
print(np.zeros((3,2), dtype = np.int8))

[[0 0]
 [0 0]
 [0 0]]


**Array of specified size, filled with ones**

In [7]:
print(np.ones((2,3), dtype = np.int8))

[[1 1 1]
 [1 1 1]]


**Array filled with the element in the diagonal with 1s**

In [8]:
print(np.eye(3, dtype = np.int8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Convert list to ndarry**

In [10]:
lst = [1,2,3]
x1 = np.asarray(lst)
print(x1)

[1 2 3]


**Ndarray from tupple**

In [11]:
tpl_1 = (1,2,3)
x2 = np.asarray(tpl_1)
print(x2)

[1 2 3]


**NDARRAY from list of Tupple**

In [27]:
tpl_2 = [(1,2,3),(4,5)]
x3 = np.asarray(tpl_2, dtype = object)
print(x3, '\n shape', x3.shape)

[(1, 2, 3) (4, 5)] 
 shape (2,)


**Mathematical Operations on Arrays**

In [29]:
x4 = np.array([10,20,30,40,50])
print("Add", x4 + 5)
print("Subtract", x4 - 5)
print("Multiply", x4 * 5)
print("Divide", x4 / 5.0)

Add [15 25 35 45 55]
Subtract [ 5 15 25 35 45]
Multiply [ 50 100 150 200 250]
Divide [ 2.  4.  6.  8. 10.]


**Slicing in 1D Array**

In [12]:
x5 = np.array([6,7,8,9,23])
print(x5[:5])
print(x5[::2])
print(x5[::-1])
print(x5[-1:-5:1])
print(x5[-1:5:1])
print(x5[-1:-5:-1])
print(x5[2:-2])

[ 6  7  8  9 23]
[ 6  8 23]
[23  9  8  7  6]
[]
[23]
[23  9  8  7]
[8]


**Slicing 2-D Array**

Syntax: Array_name[start:stop:step,start:stop:step]

In [30]:
x6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x6[:2:1])
print("----------------")
print(x6[::2,])
print("----------------")
print(x6[1:-1,])
print("----------------")
print(x6[:,:1])
print("----------------")
print(x6[:1,:1])
print("----------------")

[[1 2 3]
 [4 5 6]]
----------------
[[1 2 3]
 [7 8 9]]
----------------
[[4 5 6]]
----------------
[[1]
 [4]
 [7]]
----------------
[[1]]
----------------
