<a href="https://colab.research.google.com/github/harshsinha-12/GoogleCollabTutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The Data Structure (object) defined in Numpy is an N-dimentional array called**

In [1]:
import numpy as np

In [ ]:
array_name = numpy.array(data, dtype = None, ndimin)

In [ ]:
a1 = np.array([1,2,3])

In [ ]:
# dimension: 2
a3 = np.array([1,2,3], dtype = 'int32')
print(a4, '\n dtype:', a4.dtype)

Reshape

In [ ]:
a5 = np.array([[1,2,3],[4,5,6]])
print(a5, '\n shape:', a5.shape)
a5.shape = (3,2)
print(a5, '\n shape:', a5.shape)

In [ ]:
a6 = np.array([[1,2,3],[4,5,6]])
print(a6, '\n shape:', a6.shape)
a7 = a6.reshape(3,2)
print(a7, '\n shape:', a7.shape)

**Sequence**

Stntax:
numpy.arange(start,stop,step,dtype =None)

In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(np.arange(1,10,0.5))


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


Array of specified size, filled with zeros

In [4]:
print(np.zeros((3,2), dtype = np.int8))

[[0 0]
 [0 0]
 [0 0]]


Array of specified size, filled with ones

In [7]:
print(np.ones((2,3), dtype = np.int8))

[[1 1 1]
 [1 1 1]]


Array filled with the element in the diagonal with 1s

In [8]:
print(np.eye(3, dtype = np.int8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Convert list to ndarry

In [10]:
lst = [1,2,3]
x1 = np.asarray(lst)
print(x1)

[1 2 3]


Ndarray from tupple

In [11]:
tpl_1 = (1,2,3)
x2 = np.asarray(tpl_1)
print(x2)

[1 2 3]


NDARRAY from list of Tupple

Mathematical Operations on Arrays

In [ ]:
x4 = np.array([10,20,30,40,50])
print("")

Slicing in 1D Array

In [12]:
x5 = np.array([6,7,8,9,23])
print(x5[:5])
print(x5[::2])
print(x5[::-1])
print(x5[-1:-5:1])
print(x5[-1:5:1])
print(x5[-1:-5:-1])
print(x5[2:-2])

[ 6  7  8  9 23]
[ 6  8 23]
[23  9  8  7  6]
[]
[23]
[23  9  8  7]
[8]


Slicing 2-D Array

Syntax: Array_name[start:stop:step,start:stop:step]

In [13]:
x6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x6[:1,])

[[1 2 3]]
